config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users

  root 'welcome#index'

  namespace :weather do
    resource :search, only: [:show]
  end

  namespace :admin do
    resource :cities, only: %i[new create]
  end
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/city.rb
# frozen_string_literal: true

class City < ApplicationRecord
  validates :name, :lat, :lon, presence: true
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/admin/base_controller.rb
# frozen_string_literal: true

module Admin
  class BaseController < ApplicationController
    layout 'admin'

    before_action :authorize_admin_access

    private

    def authorize_admin_access
      authorize %i[admin dashboard], :index?
    end
  end
end

app/controllers/admin/cities_controller.rb
# frozen_string_literal: true

module Admin
  class CitiesController < Admin::BaseController
    def new
      set_cities
      @city = City.new
    end

    def create
      @city = City.new(city_params)

      if @city.save
        redirect_to new_admin_cities_path
      else
        set_cities
        render :new, status: :unprocessable_entity
      end
    end

    private

    def set_cities
      @cities = City.all
    end

    def city_params
      params.require(:city).permit(:name, :lat, :lon)
    end
  end
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
  include Pundit::Authorization

  before_action :authenticate_user!
  rescue_from Pundit::NotAuthorizedError, with: :user_not_authorized

  private

  def user_not_authorized
    redirect_to root_path
  end
end

app/controllers/weather/searches_controller.rb
# frozen_string_literal: true

module Weather
  class SearchesController < ApplicationController
    def show
      @info = {
        weather: ::Weather::SearchService.call(city_id: params[:city_id]),
        city_id: params[:city_id],
        cities: City.all # без пагинации для выпадающего спика
      }

      render 'welcome/index'
    end
  end
end

app/controllers/welcome_controller.rb
# frozen_string_literal: true

class WelcomeController < ApplicationController
  def index
    @info = {
      cities: City.all # без пагинации для выпадающего спика
    }
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
end

app/views/admin/cities/new.html.erb
<table class="table">
  <thead>
    <tr>
      <th scope="col">ID</th>
      <th scope="col">Название</th>
      <th scope="col">Lat</th>
      <th scope="col">Lon</th>
    </tr>
  </thead>
  <tbody>
     <% @cities.each do |city| %>
      <tr>
        <th scope="row"><%= city.id %></th>
        <td><%= city.name %></td>
        <td><%= city.lat %></td>
        <td><%= city.lon %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= bootstrap_form_for([:admin, @city]) do |f| %>
  <%= f.text_field :name %>
  <%= f.text_field :lat %>
  <%= f.text_field :lon %>
  <%= f.submit 'Создать город' %>
<% end %>

app/views/layouts/admin.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Weather</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <div class="container">
      <nav class="navbar navbar-expand-lg bg-body-tertiary">
        <div class="container-fluid">
          <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav">
              <li class="nav-item">
                <%= link_to "Главная", root_path, class: 'nav-link active' %>
              </li>
            </ul>
          </div>
        </div>
      </nav>
    </div>

    <div class="container">
      <h1>Админка</h1>
      <hr>
      <%= yield %>
    </div>
  </body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Weather</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>

    <script src="https://api-maps.yandex.ru/2.1/?lang=ru_RU&amp;apikey=d9b326b3-beeb-499d-9ecb-938c75c7af75" type="text/javascript"></script>
    <script src="placemark.js" type="text/javascript"></script>
  </head>

  <body>
    <div class="container">
      <nav class="navbar navbar-expand-lg bg-body-tertiary">
        <div class="container-fluid">
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Переключатель навигации">
            <span class="navbar-toggler-icon"></span>
          </button>

          <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav">
              <li class="nav-item">
                <%= link_to "Главная", root_path, class: 'nav-link active' %>
              </li>
              <li class="nav-item">
                <%= link_to "Выйти", destroy_user_session_path, data: { turbo_method: :delete }, class: "nav-link" %>
              </li>
            </ul>
          </div>
        </div>
      </nav>
    </div>

    <div class="container">
      <h1>Прогноз погоды</h1>
      <hr>
      <%= yield %>
    </div>
  </body>
</html>

app/views/welcome/index.html.erb
<%= bootstrap_form_tag url: weather_search_path, method: :get, data: { turbo: false } do |f| %>
  <%= f.select :city_id, @info[:cities]&.map { |city| [city.name, city.id] },
    {
      label: 'Выберите город:',
      selected: @info[:city_id]
    },
    {
      class: 'selectpicker'
    }
  %>
  <%= f.submit 'Посмотреть погоду', class: "btn btn-success" %>
<% end %>

<hr>

<% if @info.dig(:weather).present? %>
  <div class="alert alert-info" role="alert">
    Температура: <b><%= @info.dig(:weather, :main, :temp) %></b> градусов
  </div>
  <br />
  <div id="map" style="width: 600px; height: 400px"></div>
<% end %>


<script>
ymaps.ready(init);

function init() {
    // Создаем карту.
    var myMap = new ymaps.Map("map", {
            center: ['<%= @info.dig(:weather, :coord, :lat) %>', '<%= @info.dig(:weather, :coord, :lon) %>'],
            zoom: 10
        }, {
            searchControlProvider: 'yandex#search'
        });

    // Создаем круг.
    var myCircle = new ymaps.Circle([
        // Координаты центра круга.
        ['<%= @info.dig(:weather, :coord, :lat) %>', '<%= @info.dig(:weather, :coord, :lon) %>'],
        // Радиус круга в метрах.
        10000
    ], {
        // Описываем свойства круга.
        // Содержимое балуна.
        balloonContent: "Радиус круга - 10 км",
        // Содержимое хинта.
        hintContent: "Подвинь меня"
    }, {
        // Задаем опции круга.
        // Включаем возможность перетаскивания круга.
        draggable: true,
        // Цвет заливки.
        // Последний байт (77) определяет прозрачность.
        // Прозрачность заливки также можно задать используя опцию "fillOpacity".
        fillColor: "#00FFFF50",
        // Цвет обводки.
        strokeColor: "#E0FFFF",
        // Прозрачность обводки.
        strokeOpacity: 0.8,
        // Ширина обводки в пикселях.
        strokeWidth: 5
    });

    // Добавляем круг на карту.
    myMap.geoObjects.add(myCircle);
}
</script>